name: Clippo
options:
  bundleIdPrefix: com.clippo
targets:
  Clippo:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources
        excludes:
          - Resources
      - path: Sources/Resources
        buildPhase: resources
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.clippo.macos
      INFOPLIST_FILE: Info.plist
      ENTITLEMENTS_FILE: Clippo.entitlements
      ENABLE_HARDENED_RUNTIME: true
      CODE_SIGN_IDENTITY: "-"
      PRODUCT_NAME: Clippo
